name: Deploy to GitHub Pages (main branch)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy built site to root (for GitHub Pages)
        run: |
          mkdir temp
          cp -r dist/* temp/
          rm -rf *
          mv temp/* ./
          rm -rf temp

      - name: Commit and push built site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy static site" || echo "No changes to commit"
          git push origin main
